[tool.poetry]
name = "Poc-it"
version = "0.1.0"
description = "Sistema inteligente capaz de transformar una descripcion funcional en una PoC backend basica, funcional y versionada en Git, validando la reduccion de tiempo frente a un desarrollo manual"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11.0, <3.14"
crewai = ">=0.1.24"
python-dotenv = ">=1.0.0"
langchain = ">=0.1.0"
langchain-community = ">=0.0.1"
langchain-ollama = ">=0.1.0"
crewai-tools = ">=0.1.0"
duckduckgo-search = ">=3.8.0"
ddgs = "^9.10.0"
litellm = "^1.81.14"
tool = "^0.8.0"

[tool.pyright]
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']
